# Generated by Django 5.1.4 on 2024-12-17 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "products",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["name"], name="product_name_idx")],
            },
        ),
        migrations.CreateModel(
            name="SalesRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_refund", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stores.store"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Record",
                "verbose_name_plural": "Sales Records",
                "db_table": "sales_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.product"
                    ),
                ),
                (
                    "sales_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales.salesrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Item",
                "verbose_name_plural": "Sales Items",
                "db_table": "sales_items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="salesrecord",
            index=models.Index(fields=["user"], name="sales_user_idx"),
        ),
        migrations.AddIndex(
            model_name="salesrecord",
            index=models.Index(fields=["store"], name="sales_store_idx"),
        ),
        migrations.AddIndex(
            model_name="salesrecord",
            index=models.Index(fields=["is_refund"], name="sales_refund_idx"),
        ),
        migrations.AddIndex(
            model_name="salesitem",
            index=models.Index(fields=["sales_record"], name="sales_item_record_idx"),
        ),
        migrations.AddIndex(
            model_name="salesitem",
            index=models.Index(fields=["product"], name="sales_item_product_idx"),
        ),
    ]
